version: "3.8"
services:

  tomcat-ncwms:
    container_name: tomcat-ncwms

    # External image for creating ncWMS docker containers
    image: guygriffiths/ncwms

    volumes:
      - C:\Users\Moos-Hyde\Documents\Hyde-Platform\prototype\raster-Backend\config.xml:/usr/local/tomcat/.ncWMS2/config.xml # config file for ncWMS
      - C:\Users\Moos-Hyde\Documents\Hyde-Platform\prototype\raster-Backend\tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml # user file for tomcat
      - ./WMS/netCDF:/data/netCDF # netCDF data

    ports:
      - 8080:8080

    # now interactable with: docker compose exec tomcat-ncwms bash
    stdin_open: true
    tty: true

    # Requered for running on server, for some reason
    ulimits:
      nofile: 65536

    # Healthcheck such that the fill-container can start after ncWMS is checked to have launched correctly
    healthcheck:
      test: curl --fail http://localhost:8080/ncWMS || exit 1
      interval: 20s
      retries: 5
      start_period: 10s
      timeout: 10s

  ncwms-fill:
    container_name: ncwms-fill

    # Build image from the ./fill-db/Dockerfile
    build: ./WMS

    # Contains necessary password
    env_file:
      - C:\Users\Moos-Hyde\Documents\Hyde-Platform\.env

    # make again interactible
    stdin_open: true
    tty: true

    # Starts after succesful healthcheck of timeseries-database container
    depends_on:
      tomcat-ncwms:
        condition: service_healthy

    # copy data into container
    volumes:
      - ./WMS/netCDF:/data/netCDF