version: "3.8"
services:

  tomcat-ncwms:
    container_name: tomcat-ncwms

    image: guygriffiths/ncwms

    volumes:
      # !!!!!! Important !!!!! password encrypted with SHA-1!!!!! NOT SHA-512. 
      - /home/moos/Hyde-Platform/prototype/ncWMS/config.xml:/usr/local/tomcat/.ncWMS2/config.xml
      - /home/moos/Hyde-Platform/prototype/ncWMS/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./fill-db/netCDF:/data/netCDF

    ports: 
      - 8080:8080
      

    # now interactable with: docker compose exec tomcat-ncwms bash
    stdin_open: true 
    tty: true

    healthcheck:
      test: curl --fail http://localhost:8080/ncWMS || exit 1
      interval: 20s
      retries: 5
      start_period: 10s
      timeout: 10s


  ncwms-fill:
    container_name: ncwms-fill

    # Build image from the ./fill-db/Dockerfile
    build: ./fill-db
    env_file:
      - /home/moos/Hyde-Platform/.env

    stdin_open: true 
    tty: true

    # Starts after succesful healthcheck of timeseries-database container
    depends_on: 
      tomcat-ncwms:
        condition: service_healthy

    # copy data into container
    volumes:
      - ./fill-db/netCDF:/data/netCDF