version: "3"
services:
  timeseries-database:
    container_name: timeseries-database
    image: postgres 
    environment:
      DEBUG: 0
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: timeseries
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  timeseries-fill:
    container_name: timeseries-fill
    build: ./fill-db
    environment:
      DEBUG: 0
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on: 
      timeseries-database:
        condition: service_healthy
    volumes:
      - ./fill-db/data/txt:/app/data/txt

  timeseries-api:
    container_name: timeseries-api
    build: ./api
    environment:
      DEBUG: 0
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      timeseries-fill:
        condition: service_completed_successfully
    ports: 
      - 8000:8000